version: '3.3'
services: 
  app:
    image: nodeapp
    build: .
    ports:
      - '9000:3000'
    environment:
      - MONGO_URI=mongodb://mongo_db/nodeapp
    networks:
      - nodemernapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
     

  db:
    image: mongo:3.0.15
    volumes:
      - mongo-db:/data/db
    networks:
      nodemernapp:
        aliases:
          - "mongo_db"
networks:
  nodemernapp:
    driver: bridge
volumes:
  mongo-db: