version: "3"
services:
  web:
    build: .
    image: phase1/flask
    environment: 
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    networks:
      - phase1_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  redis:
    image: redis:4.0.11-alpine
    networks:
      - phase1_default
networks:
  phase1_default:

