FROM nginx:1.15-alpine

WORKDIR /usr/share/nginx/html

COPY index.html index.html

# docker build . -t <username/imagename>
#docker container run --name whatever -d -p 8000:80  

# docker kill $(docker ps -q)
# lsof -wni tcp:3000 