version: '3'

services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - "5000:80"
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  redis:
    image: redis:3.2
    networks:
      - frontend
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
  db:
    image: postgres:9.4
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - '5001:80'
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  db:

  